server:
  port: 8087
  
# Configurar Actuator
management:
  endpoints:
    web:
      exposure:
        exclude:
        include: health
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true