spring:
  application:
    name: kafka-streams-aggregate-sample
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: 10.0.75.1:29092,10.0.75.1:39092,10.0.75.1:49092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
      bindings:
        aggregate-in-0:
          destination: bar
