spring:
  application:
    name: Greetings
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.0.75.1:29092,10.0.75.1:39092,10.0.75.1:49092
      bindings:
        greetings-in:
          destination: foo
          contentType: application/json
        greetings-out:
          destination: foo
          contentType: application/json
