server:
  port: ${port:8083}

#Conexion con Admin APP
spring:
  application:
    name: heroes
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: prueba
        url: http://localhost:8081
        username: admin
        password: pass
        
# Configurar Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

# Configurar Actuator
management:
  endpoints:
    jmx:
      exposure:
        exclude: shutdown
        include: "*"
    web:
      exposure:
        exclude:
        # include: health,info,metrics
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
logging:
  file: milog.txt
info:
  tags:
    environment: prueba
  app:
    name: Heroes
    description: Servicio que implementa el backend de heroes
    version: 1.0.0      