spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # http://localhost:8088/caller/caller es equivalente a http://caller-service/caller
      # http://localhost:8088/caller/caller/slow es equivalente a http://caller-service/caller/slow
        - id: caller-service
          uri: lb://caller-service
          predicates:
            - Path=/caller/**
          filters:
            - RewritePath=/caller/(?<path>.*), /$\{path}
        - id: callme-service
          uri: lb://callme-service
          predicates:
            - Path=/callme/**
          filters:
            - RewritePath=/callme/(?<path>.*), /$\{path}